version: '3'
services:
  arma_server:
    build: ./arma3-docker
    ports:
      - "2302-2305:2302-2305/udp"
    volumes:
      - "${HOST_ARMA_DIR}/key:/arma3/keys"
      - "${HOST_ARMA_DIR}/mods:/arma3/mods"
      - "${HOST_ARMA_DIR}/mpmissions:/arma3/mpmissions"
      - "${HOST_ARMA_DIR}/server:/server"
      - "${HOST_ARMA_DIR}/profiles:/profiles"
    command: ["-cfg=/server/basic.cfg", "-config=/server/server.cfg", "-mod=mods/@tembelan_island;"]

    
